export const site = {
  name: "Headie",
  handle: "@iamheadie",
  tagline: "AI Creator · Video Editor & Motion Designer",
  thesis: "Ideas, made to linger.",
  hero: ["I turn ideas", "into films", "you can feel."],
  email: "degenvick@gmail.com",
  bio: "AI creator, video editor and motion designer. I turn ideas into short-form films — narratives, music videos, explainers and experiments — crafted to stop the scroll and stay with you.",
  about:
    "I make short films with AI as my camera and crew. I build worlds one prompt at a time — obsessing over palette, continuity and rhythm until a generated clip reads like it was directed, not summoned. The goal is never the tool. It's the moment the story lands.",
  role: "AI Creator · Video Editor & Motion Designer",
  location: "Nigeria · Working worldwide",
  socials: {
    x: "https://x.com/iamheadie",
    xHandle: "iamheadie",
    telegram: "https://t.me/Headiee",
    github: "https://github.com/iamHeadie",
    xPosts: [
      "https://x.com/iamheadie/status/2088153273656017048",
      "https://x.com/iamheadie/status/2088527068141138370",
      "https://x.com/iamheadie/status/2093251004732985753",
      "https://x.com/iamheadie/status/2091946079692394902",
      "https://x.com/iamheadie/status/2090682253324017869",
      "https://x.com/iamheadie/status/2065064823855931628",
      "https://x.com/iamheadie/status/2062055439777382419",
    ],
  },
  tools: [
    { name: "invideo Agent", role: "Generation & continuity" },
    { name: "Minimax", role: "Motion & video model" },
    { name: "Hyperframes", role: "Programmatic frames" },
    { name: "Claude", role: "Scripting & direction" },
    { name: "After Effects", role: "Compositing & polish" },
    { name: "CapCut", role: "Edit & sound" },
  ],
  stats: [
    { k: "Films shipped", v: "Short-form AI film" },
    { k: "Aspect", v: "Built for the feed" },
    { k: "Turnaround", v: "Days, not weeks" },
  ],
} as const;
